/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => FederationSyncPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  databaseUrl: "",
  apiKey: ""
};
var FederationSyncPlugin = class extends import_obsidian.Plugin {
  async onload() {
    console.log("Loading Federation Sync plugin...");
    await this.loadSettings();
    this.addSettingTab(new FederationSyncSettingTab(this.app, this));
    this.registerEvent(
      this.app.metadataCache.on("changed", (file) => {
        this.handleMetadataChange(file);
      })
    );
    this.registerEvent(
      this.app.vault.on("create", (file) => {
        if (file instanceof import_obsidian.TFile) {
          this.handleFileCreate(file);
        }
      })
    );
    this.registerEvent(
      this.app.vault.on("delete", (file) => {
        if (file instanceof import_obsidian.TFile) {
          this.handleFileDelete(file);
        }
      })
    );
    this.registerEvent(
      this.app.vault.on("rename", (file, oldPath) => {
        if (file instanceof import_obsidian.TFile) {
          this.handleFileRename(file, oldPath);
        }
      })
    );
  }
  onunload() {
    console.log("Unloading Federation Sync plugin...");
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  // --- Real-time Sync Handlers ---
  async handleMetadataChange(file) {
    const cache = this.app.metadataCache.getFileCache(file);
    console.log(`[Federation Sync] Metadata changed for file: ${file.path}`);
    await this.pushToFederation("UPDATE_METADATA", file, cache);
  }
  async handleFileCreate(file) {
    console.log(`[Federation Sync] File created: ${file.path}`);
    await this.pushToFederation("CREATE_FILE", file);
  }
  async handleFileDelete(file) {
    console.log(`[Federation Sync] File deleted: ${file.path}`);
    await this.pushToFederation("DELETE_FILE", file);
  }
  async handleFileRename(file, oldPath) {
    console.log(`[Federation Sync] File renamed from ${oldPath} to ${file.path}`);
    await this.pushToFederation("RENAME_FILE", file, null, oldPath);
  }
  /**
   * Core function to push updates to the Federation Database.
   * Needs to be implemented with the chosen DB adapter / API client.
   */
  async pushToFederation(action, file, cache, oldPath) {
    if (!this.settings.databaseUrl) {
      return;
    }
    try {
      const payload = {
        action,
        vaultName: this.app.vault.getName(),
        filePath: file.path,
        oldPath,
        metadata: cache || null,
        timestamp: Date.now()
      };
      const targetUrl = this.settings.databaseUrl || "http://127.0.0.1:3001/ingest/vault";
      await fetch(targetUrl, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          "Authorization": `Bearer ${this.settings.apiKey}`
        },
        body: JSON.stringify(payload)
      });
      console.debug(`[Federation Sync] Successfully pushed ${action} for ${file.path}`);
    } catch (error) {
      console.error(`[Federation Sync] Error pushing to Federation DB:`, error);
    }
  }
};
var FederationSyncSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Federation Sync Settings" });
    new import_obsidian.Setting(containerEl).setName("Database Connection URL / API Endpoint").setDesc("The endpoint or connection string for the Federation database.").addText((text) => text.setPlaceholder("Enter URL").setValue(this.plugin.settings.databaseUrl).onChange(async (value) => {
      this.plugin.settings.databaseUrl = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("API Key / Auth Token").setDesc("Authentication token required for the Federation database.").addText((text) => text.setPlaceholder("Enter token").setValue(this.plugin.settings.apiKey).onChange(async (value) => {
      this.plugin.settings.apiKey = value;
      await this.plugin.saveSettings();
    }));
  }
};
